name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
            maturin-args: "--zig --compatibility manylinux2014"
          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
            maturin-args: "--zig --compatibility manylinux2014"
          - os: macos-15
            target: aarch64-apple-darwin
            maturin-args: ""
          - os: macos-14
            target: x86_64-apple-darwin
            maturin-args: ""
          - os: windows-2025
            target: x86_64-pc-windows-msvc
            maturin-args: ""
          - os: windows-2025
            target: aarch64-pc-windows-msvc
            maturin-args: ""
    uses: ./.github/workflows/_build-and-test.yml
    with:
      runner: ${{ matrix.os }}
      target: ${{ matrix.target }}
      maturin-args: ${{ matrix.maturin-args }}
